"""
Train a causal LM (LoRA, 4-bit) on the textual trajectory prompts
generated by the preprocessing pipeline.

Notes
-----
- Make sure you `pip install` the following in your environment:
    transformers accelerate peft datasets bitsandbytes huggingface_hub
- Login to Hugging Face if the model is gated.
- Run the configured workflow from the command line, or use run_train(...)
  directly for custom experiments.
"""

from __future__ import annotations

import json
import os
import random
import shutil
from pathlib import Path
from typing import Any, Iterable, Mapping, Tuple

import numpy as np

from configs import preprocessing_config as pc
from text_utils import read_json, sequence_sha256, sha256_file, verify_canonical_prompts

_DEFAULT_DTYPE = object()


def _set_seed(seed: int):

    import torch
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    # Best-effort determinism (may impact throughput; some ops are still nondeterministic)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def _resolve_prompt_paths(use_safety: bool, prompt_prefix: str | None = None) -> Tuple[str, str, str]:
    """
    Return (train_json, val_json, test_json) absolute paths for prompt files.
    - If prompt_prefix is provided, load `{prefix}_{split}_trajs.json` from CURRENT_DATA_DIR.
    - Otherwise, choose safety vs non-safety defaults.
    """
    if prompt_prefix:
        data_dir = pc.CURRENT_DATA_DIR
        train_json = os.path.join(data_dir, f"{prompt_prefix}_train_trajs.json")
        val_json = os.path.join(data_dir, f"{prompt_prefix}_validation_trajs.json")
        test_json = os.path.join(data_dir, f"{prompt_prefix}_test_trajs.json")
    elif use_safety:
        data_dir = pc.SAFETY_DATA_DIR
        train_json = os.path.join(data_dir, "safety_textual_train_trajs.json")
        val_json = os.path.join(data_dir, "safety_textual_validation_trajs.json")
        test_json = os.path.join(data_dir, "safety_textual_test_trajs.json")
    else:
        data_dir = pc.CURRENT_DATA_DIR
        train_json = os.path.join(data_dir, "textual_train_trajs.json")
        val_json = os.path.join(data_dir, "textual_validation_trajs.json")
        test_json = os.path.join(data_dir, "textual_test_trajs.json")

    for p in (train_json, val_json, test_json):
        if not os.path.exists(p):
            raise FileNotFoundError(f"Prompt file not found: {p}")
    return train_json, val_json, test_json


def _load_hf_datasets(train_json: str, val_json: str, test_json: str):

    from datasets import Dataset
    with open(train_json, "r") as f:
        train_texts = json.load(f)
    with open(val_json, "r") as f:
        val_texts = json.load(f)
    with open(test_json, "r") as f:
        test_texts = json.load(f)

    train_ds = Dataset.from_dict({"text": train_texts})
    val_ds = Dataset.from_dict({"text": val_texts})
    test_ds = Dataset.from_dict({"text": test_texts})
    return train_ds, val_ds, test_ds


def make_tokenize_and_mask_fn(tokenizer, max_length: int):
    """
    Returns a function that:
      - tokenizes text
      - creates labels identical to input_ids
      - masks all tokens up to the start of "<answer>:" with -100 (ignored in loss)
    """
    answer_marker = "<answer>:"

    def _fn(batch):
        # Encode full text
        enc = tokenizer(
            batch["text"],
            padding="longest",
            truncation=True,
            max_length=max_length,
            return_tensors="pt",
        )
        input_ids = enc["input_ids"]
        labels = input_ids.clone()

        # For each sample, figure out how many tokens belong to the question part
        for i, full_text in enumerate(batch["text"]):
            idx = full_text.find(answer_marker)
            if idx == -1:
                # No answer marker; ignore the whole sample in loss
                labels[i, :] = -100
                continue

            # Tokenize the substring up to answer start; its token length is the mask cutoff
            q_text = full_text[:idx]
            q_enc = tokenizer(
                q_text,
                truncation=True,
                max_length=max_length,
                return_tensors="pt",
            )
            q_len = q_enc["input_ids"].shape[1]

            # If the full sequence got truncated before reaching the answer, we may end up
            # masking the entire thing (OK—no loss from this sample).
            cutoff = min(q_len, labels.size(1))
            labels[i, :cutoff] = -100

        enc["labels"] = labels
        return enc

    return _fn


def run_train(
    *,
    dataset: str = "CHICAGO", # or "NYC"
    traj_len: int = 20, # or any other length
    crime_radius: int = 1000, # or any other length
    crime_time_weeks: int = 3, # or any other length
    base_dir: str = "/absolute/path/to/SafetyIsAllYouNeed", # change to your own dir
    use_safety: bool = True, # or False
    prompt_prefix: str | None = None,
    seed: int | None = 42,
    # Model / tokenizer
    model_name: str = "meta-llama/Llama-3.1-8B-Instruct",
    use_4bit: bool = True,
    torch_dtype = _DEFAULT_DTYPE,
    # LoRA fine tuning config
    lora_r: int = 16,
    lora_alpha: int = 32,
    lora_dropout: float = 0.05,
    target_modules: Iterable[str] = ("q_proj", "v_proj"),
    # Tokenization
    max_length: int = 2048,
    # Training
    num_train_epochs: int = 3,
    lr: float = 2e-5,
    warmup_steps: int = 20,
    weight_decay: float = 0.0,
    per_device_train_batch_size: int = 1,
    gradient_accumulation_steps: int = 1,
    save_eval_steps: int = 500,              # save & eval interval
    fp16: bool = True,
    # Output
    output_root: str = "models",             # relative to base_dir
):
    """
    Single training run with the given hyperparameters.
    """

    import torch
    from transformers import (
        AutoTokenizer,
        AutoModelForCausalLM,
        BitsAndBytesConfig,
        TrainingArguments,
        Trainer
    )
    from peft import LoraConfig, get_peft_model
    if torch_dtype is _DEFAULT_DTYPE:
        torch_dtype = torch.float16
    if seed is not None:
        _set_seed(int(seed))
    # Config paths for this dataset/hparam combo
    pc.update_config(dataset, traj_len, crime_radius, crime_time_weeks, base_dir=base_dir)
    # Locate training files
    train_json, val_json, test_json = _resolve_prompt_paths(use_safety, prompt_prefix=prompt_prefix)
    train_ds, val_ds, test_ds = _load_hf_datasets(train_json, val_json, test_json)
    # Tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    # Model (4-bit quantized by default) + LoRA fine-tuning
    quant_cfg = None
    if use_4bit:
        quant_cfg = BitsAndBytesConfig(load_in_4bit=True)

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map="auto",
        torch_dtype=torch_dtype,
        quantization_config=quant_cfg,
    )

    lora_cfg = LoraConfig(
        r=lora_r,
        lora_alpha=lora_alpha,
        target_modules=list(target_modules),
        lora_dropout=lora_dropout,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_cfg)
    model.print_trainable_parameters()
    # Tokenization + masking
    tok_fn = make_tokenize_and_mask_fn(tokenizer, max_length=max_length)
    train_tok = train_ds.map(tok_fn, batched=True, remove_columns=["text"])
    val_tok = val_ds.map(tok_fn, batched=True, remove_columns=["text"])
    test_tok = test_ds.map(tok_fn, batched=True, remove_columns=["text"])  # optional

    train_tok.set_format(type="torch")
    val_tok.set_format(type="torch")
    test_tok.set_format(type="torch") # optional
    # Training args
    # Build a scoped output dir, e.g. models/CHICAGO/traj_len-15/crime_radius-250m/crime_time-4w/Llama-3.1-8B-Instruct_w_safety
    scope_dir = os.path.join(
        base_dir,
        output_root,
        pc.DATASET,
        f"traj_len-{traj_len}",
        f"crime_radius-{crime_radius}m",
        f"crime_time-{crime_time_weeks}w",
        f"{model_name.split('/')[-1]}_{'w' if use_safety else 'wo'}_safety",
    )
    os.makedirs(scope_dir, exist_ok=True)
    training_args = TrainingArguments(
        output_dir=scope_dir,
        num_train_epochs=num_train_epochs,
        learning_rate=lr,
        warmup_steps=warmup_steps,
        weight_decay=weight_decay,
        per_device_train_batch_size=per_device_train_batch_size,
        gradient_accumulation_steps=gradient_accumulation_steps,
        evaluation_strategy="steps",
        save_strategy="steps",
        eval_steps=save_eval_steps,
        save_steps=save_eval_steps,
        load_best_model_at_end=True,
        metric_for_best_model="loss",
        greater_is_better=False,
        logging_steps=save_eval_steps,
        save_total_limit=3,
        fp16=fp16,
        dataloader_num_workers=2,
        report_to="none",  # set to "wandb" or "tensorboard" if desired
    )
    # Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_tok,
        eval_dataset=val_tok,
        tokenizer=tokenizer,
    )
    # Train
    torch.cuda.empty_cache()
    trainer.train()
    # Persist the best checkpoint to a clean "best" folder + tokenizer
    best_ckpt = trainer.state.best_model_checkpoint or scope_dir
    final_dir = os.path.join(scope_dir, "best")
    os.makedirs(final_dir, exist_ok=True)
    shutil.copytree(best_ckpt, final_dir, dirs_exist_ok=True)
    tokenizer.save_pretrained(final_dir)
    print(f"Best checkpoint: {best_ckpt}")
    print(f"Final model (with tokenizer) saved to: {final_dir}")


ANSWER_MARKER = "<answer>:"


def select_row(config: Mapping[str, Any], row_key: str) -> Mapping[str, Any]:
    matches = [row for row in config["rows"] if row["row_key"] == row_key]
    if len(matches) != 1:
        raise ValueError(f"Expected one configuration for {row_key!r}, found {len(matches)}")
    return matches[0]


def prompt_paths(repo_root: Path, config: Mapping[str, Any], row: Mapping[str, Any]) -> dict[str, Path]:
    data_root = repo_root / config["data_profiles"][row["city"]]["path"]
    if row["prompt_variant"] == "with_safety":
        return {
            split: data_root / "safety" / f"safety_textual_{split}_trajs.json"
            for split in ("train", "validation", "test")
        }
    return {
        split: data_root / f"textual_{split}_trajs.json"
        for split in ("train", "validation", "test")
    }


def load_and_verify_prompts(
    repo_root: Path, config: Mapping[str, Any], row: Mapping[str, Any],
    *, verify_manifest: bool = True,
) -> dict[str, list[str]]:
    profile = config["data_profiles"][row["city"]]
    if verify_manifest:
        verify_canonical_prompts(repo_root / profile["path"])
    prompts = {
        split: json.loads(path.read_text(encoding="utf-8"))
        for split, path in prompt_paths(repo_root, config, row).items()
    }
    expected = profile["prompt_sequence_sha256"][row["prompt_variant"]]
    for split, values in prompts.items():
        observed = sequence_sha256(values)
        if observed != expected[split]:
            raise ValueError(f"{row['row_key']} {split} prompt sequence hash changed")
    return prompts


def verify_training_recipe(manifest, config, row):
    """Check that a training manifest matches the configured training contract."""
    expected = {
        "contract": config["contract"],
        "serializer_version": config["serializer_version"],
        "model": config["models"][row["model"]],
        "training": config["training_defaults"],
        "prompt_sequence_sha256": config["data_profiles"][row["city"]]["prompt_sequence_sha256"][row["prompt_variant"]],
    }
    for key, value in expected.items():
        if manifest.get(key) != value:
            raise ValueError(f"Training manifest mismatch: {key}")
    for key in ("row_key", "city", "variant", "prompt_variant", "model", "seed", "base_precision", "checkpoint"):
        if manifest.get("row", {}).get(key) != row[key]:
            raise ValueError(f"Training row mismatch: {key}")
    return manifest


def verify_training_manifest(adapter, config, row):
    """Check a locally trained adapter and its training manifest."""
    adapter = Path(adapter).resolve()
    manifest = verify_training_recipe(
        read_json(adapter.parent.parent / "run_manifest.json"), config, row
    )
    if adapter.name != f"checkpoint-{row['checkpoint']['step']}":
        raise ValueError("Use the configured checkpoint produced by your training run")
    if not (adapter / "adapter_config.json").is_file():
        raise ValueError("Training checkpoint has no adapter_config.json")
    if not any((adapter / name).is_file() for name in ("adapter_model.safetensors", "adapter_model.bin")):
        raise ValueError("Training checkpoint has no adapter weights")
    return manifest


def set_seed(seed: int) -> None:
    import numpy as np
    import torch

    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def make_tokenize_fn(tokenizer, max_length: int):
    def tokenize(batch):
        encoded = tokenizer(
            batch["text"],
            padding="longest",
            truncation=True,
            max_length=max_length,
            return_tensors="pt",
        )
        labels = encoded["input_ids"].clone()
        for index, text in enumerate(batch["text"]):
            answer_index = text.find(ANSWER_MARKER)
            if answer_index < 0:
                labels[index, :] = -100
                continue
            question_length = tokenizer(
                text[:answer_index],
                truncation=True,
                max_length=max_length,
                return_tensors="pt",
            )["input_ids"].shape[1]
            labels[index, : min(question_length, labels.size(1))] = -100
        encoded["labels"] = labels
        return encoded

    return tokenize


def audit_lengths(tokenizer, prompts: Mapping[str, list[str]], max_length: int) -> dict:
    result = {"max_length": max_length, "splits": {}}
    for split, values in prompts.items():
        lengths = [len(tokenizer(text, add_special_tokens=True)["input_ids"]) for text in values]
        result["splits"][split] = {
            "count": len(lengths),
            "maximum": max(lengths, default=0),
            "exceeding_count": sum(length > max_length for length in lengths),
        }
    return result


def run_training(
    *,
    repo_root: str | Path,
    config_path: str | Path,
    row_key: str,
    output_dir: str | Path,
    resume_from_checkpoint: str | None = None,
) -> dict[str, Any]:
    import torch
    from datasets import Dataset
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
    from transformers import (
        AutoModelForCausalLM,
        AutoTokenizer,
        BitsAndBytesConfig,
        Trainer,
        TrainerCallback,
        TrainingArguments,
    )

    root = Path(repo_root).resolve()
    config = pc.load_model_config(config_path)
    row = select_row(config, row_key)
    defaults = config["training_defaults"]
    model_contract = config["models"][row["model"]]
    run_dir = Path(output_dir).resolve()
    if run_dir.exists() and any(run_dir.iterdir()) and resume_from_checkpoint is None:
        raise FileExistsError(f"Training output directory must be empty: {run_dir}")
    if resume_from_checkpoint is not None:
        resume_path = Path(resume_from_checkpoint).resolve()
        if resume_path.parent != run_dir / "checkpoints" or not resume_path.is_dir():
            raise ValueError("Resume from a checkpoint inside this run's checkpoints directory")
        verify_training_recipe(read_json(run_dir / "run_manifest.json"), config, row)
    if not torch.cuda.is_available():
        raise RuntimeError("The configured 4-bit training recipe requires a CUDA GPU")
    prompts = load_and_verify_prompts(root, config, row)
    set_seed(int(row["seed"]))
    run_dir.mkdir(parents=True, exist_ok=True)

    tokenizer = AutoTokenizer.from_pretrained(
        model_contract["id"], revision=model_contract["revision"], use_fast=True
    )
    tokenizer.pad_token = tokenizer.pad_token or tokenizer.eos_token
    length_audit = audit_lengths(tokenizer, prompts, int(defaults["max_length"]))
    if any(item["exceeding_count"] for item in length_audit["splits"].values()):
        raise ValueError("Prompt truncation is not allowed by the frozen contract")
    model_kwargs: dict[str, Any] = {
        "device_map": "auto",
        "torch_dtype": torch.float16,
        "low_cpu_mem_usage": True,
    }
    if row["base_precision"] == "bnb_default":
        model_kwargs["quantization_config"] = BitsAndBytesConfig(load_in_4bit=True)
    elif row["base_precision"] == "nf4":
        model_kwargs["quantization_config"] = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
        )
    else:
        raise ValueError(f"Unsupported frozen precision: {row['base_precision']}")
    model = AutoModelForCausalLM.from_pretrained(
        model_contract["id"], revision=model_contract["revision"], **model_kwargs
    )
    model = prepare_model_for_kbit_training(model)
    model.config.use_cache = False
    lora = defaults["lora"]
    from eval import _disable_incompatible_torchao
    _disable_incompatible_torchao()
    model = get_peft_model(
        model,
        LoraConfig(
            r=int(lora["rank"]),
            lora_alpha=int(lora["alpha"]),
            target_modules=list(lora["target_modules"]),
            lora_dropout=float(lora["dropout"]),
            bias=str(lora["bias"]),
            task_type="CAUSAL_LM",
        ),
    )
    if not any(parameter.requires_grad for parameter in model.parameters()):
        raise RuntimeError("The LoRA contract has no trainable parameters")

    tokenize = make_tokenize_fn(tokenizer, int(defaults["max_length"]))
    datasets = {
        split: Dataset.from_dict({"text": values}).map(
            tokenize, batched=True, remove_columns=["text"]
        )
        for split, values in prompts.items() if split != "test"
    }
    checkpoint_dir = run_dir / "checkpoints"
    arguments = TrainingArguments(
        output_dir=str(checkpoint_dir),
        num_train_epochs=float(defaults["epochs"]),
        learning_rate=float(defaults["learning_rate"]),
        warmup_steps=int(defaults["warmup_steps"]),
        weight_decay=float(defaults["weight_decay"]),
        per_device_train_batch_size=int(defaults["per_device_train_batch_size"]),
        gradient_accumulation_steps=int(defaults["gradient_accumulation_steps"]),
        eval_strategy="steps",
        save_strategy="steps",
        eval_steps=int(defaults["save_steps"]),
        save_steps=int(defaults["save_steps"]),
        load_best_model_at_end=True,
        metric_for_best_model="loss",
        greater_is_better=False,
        logging_steps=int(defaults["save_steps"]),
        save_total_limit=50,
        save_only_model=False,
        fp16=True,
        report_to="none",
        seed=int(row["seed"]),
        data_seed=int(row["seed"]),
    )
    selected_step = int(row["checkpoint"]["step"])
    stop_step = int(row["checkpoint"]["train_stop_step"])

    class StopAtFrozenStep(TrainerCallback):
        def on_step_end(self, training_args, state, control, **kwargs):
            if state.global_step >= stop_step:
                control.should_save = True
                control.should_training_stop = True
            return control

    manifest = {
        "contract": config["contract"],
        "serializer_version": config["serializer_version"],
        "row": row,
        "model": model_contract,
        "training": defaults,
        "prompt_sequence_sha256": config["data_profiles"][row["city"]]["prompt_sequence_sha256"][row["prompt_variant"]],
        "prompt_file_sha256": {
            split: sha256_file(path)
            for split, path in prompt_paths(root, config, row).items()
        },
        "prompt_length_audit": length_audit,
    }
    (run_dir / "run_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    trainer = Trainer(
        model=model,
        args=arguments,
        train_dataset=datasets["train"],
        eval_dataset=datasets["validation"],
        callbacks=[StopAtFrozenStep()],
    )
    train_result = trainer.train(resume_from_checkpoint=resume_from_checkpoint)
    selected = checkpoint_dir / f"checkpoint-{selected_step}"
    if not selected.is_dir():
        raise RuntimeError(f"Frozen selected checkpoint was not produced: {selected}")
    result = {
        "row_key": row_key,
        "global_step": trainer.state.global_step,
        "planned_max_steps": trainer.state.max_steps,
        "best_model_checkpoint": trainer.state.best_model_checkpoint,
        "best_metric": trainer.state.best_metric,
        "selected_checkpoint": str(selected),
        "metrics": train_result.metrics,
    }
    (run_dir / "train_result.json").write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return result


if __name__ == "__main__":
    import sys
    from batch_runner import main
    main(sys.argv[1:], command="train")
